<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GE6LMT5" failures="0" tests="11" name="Tests.TestCase1" time="33.112" errors="1" timestamp="2025-06-10T20:19:59 IST" skipped="10">
  <testcase classname="Tests.TestCase1" name="allAppLaunch" time="0.002">
    <skipped/>
  </testcase> <!-- allAppLaunch -->
  <testcase classname="Tests.TestCase1" name="allAppLaunch" time="0.008">
    <skipped/>
  </testcase> <!-- allAppLaunch -->
  <testcase classname="Tests.TestCase1" name="allAppLaunch" time="0.002">
    <skipped/>
  </testcase> <!-- allAppLaunch -->
  <testcase classname="Tests.TestCase1" name="allAppLaunch" time="0.000">
    <skipped/>
  </testcase> <!-- allAppLaunch -->
  <testcase classname="Tests.TestCase1" name="allAppLaunch" time="0.264">
    <skipped/>
  </testcase> <!-- allAppLaunch -->
  <testcase classname="Tests.TestCase1" name="allAppLaunch" time="0.001">
    <skipped/>
  </testcase> <!-- allAppLaunch -->
  <testcase classname="Tests.TestCase1" name="allAppLaunch" time="0.001">
    <skipped/>
  </testcase> <!-- allAppLaunch -->
  <testcase classname="Tests.TestCase1" name="allAppLaunch" time="0.001">
    <skipped/>
  </testcase> <!-- allAppLaunch -->
  <testcase classname="Tests.TestCase1" name="allAppLaunch" time="0.003">
    <skipped/>
  </testcase> <!-- allAppLaunch -->
  <testcase classname="Tests.TestCase1" name="allAppLaunch" time="0.003">
    <skipped/>
  </testcase> <!-- allAppLaunch -->
  <testcase classname="Tests.TestCase1" name="configTest" time="32.827">
    <error message="Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms 
Host info: host: &#039;DESKTOP-GE6LMT5&#039;, ip: &#039;192.168.1.3&#039;
Build info: version: &#039;4.33.0&#039;, revision: &#039;2c6aaad03a&#039;
System info: os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;11.0.2&#039;
Driver info: io.appium.java_client.android.AndroidDriver
Command: [null, newSession {capabilities=[Capabilities {appium:automationName: UIAutomator2, appium:deviceName: 192.168.1.23:5555, appium:udid: 192.168.1.23:5555, platformName: ANDROID}]}]
Capabilities {appium:automationName: UIAutomator2, appium:deviceName: 192.168.1.23:5555, appium:udid: 192.168.1.23:5555, platformName: ANDROID}" type="org.openqa.selenium.SessionNotCreatedException">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms 
Host info: host: 'DESKTOP-GE6LMT5', ip: '192.168.1.3'
Build info: version: '4.33.0', revision: '2c6aaad03a'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [null, newSession {capabilities=[Capabilities {appium:automationName: UIAutomator2, appium:deviceName: 192.168.1.23:5555, appium:udid: 192.168.1.23:5555, platformName: ANDROID}]}]
Capabilities {appium:automationName: UIAutomator2, appium:deviceName: 192.168.1.23:5555, appium:udid: 192.168.1.23:5555, platformName: ANDROID}
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:114)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:176)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:237)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:544)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:270)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:173)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:91)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:103)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:109)
at Tests.BaseTest.configTest(BaseTest.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:358)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- configTest -->
</testsuite> <!-- Tests.TestCase1 -->
